### PR TITLE
add keyword types import

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
waiting for bio4j/bio4j-data-import#17

**Comment by eparejatobes** [comment]
The keyword categories are imported OK; when importing keywords I get `com.thinkaurelius.titan.core.SchemaViolationException: An edge with the given label already exists on the in-vertex and the label [com.bio4j.model.UniProtGraph.KeywordsType] is in-unique`.

Probably the arity is wrong in bio4j/bio4j

**Comment by eparejatobes** [comment]
Strange; there we have

``` java
public final class KeywordsType
  extends EdgeType<Protein, Keywords, Keyword>
  implements FromAtLeastOne, ToAny
{
  // ...
}
```

**Comment by eparejatobes** [comment]
from where this is in-unique?? @laughedelic any ideas?

**Comment by laughedelic** [comment]
So was it about arities? Or the label is still in-unique?

**Comment by eparejatobes** [comment]
@laughedelic this works nicely, if a bit slow due to a lot of index queries.

**Comment by eparejatobes** [comment]
LGTM

**Pull request merged**
